#!/bin/bash

# Quick script to run migrations via Supabase SQL Editor
echo "========================================"
echo "ShopSync Database Migration"
echo "========================================"
echo ""
echo "📋 Migration file: ALL_MIGRATIONS.sql"
echo ""
echo "📝 To run migrations:"
echo ""
echo "Option 1: Using Supabase SQL Editor (Easiest)"
echo "   1. Open: https://supabase.com/dashboard/project/fgyssizbuggjqsarwiuj/sql"
echo "   2. Click '+ New query'"
echo "   3. Open file: ALL_MIGRATIONS.sql"
echo "   4. Copy all contents (Cmd+A, Cmd+C)"
echo "   5. Paste into SQL Editor (Cmd+V)"
echo "   6. Click 'Run' or press Cmd+Enter"
echo "   7. Wait for 'Success' message"
echo ""
echo "Option 2: Using Supabase CLI (After login)"
echo "   1. Get access token: https://supabase.com/dashboard/account/tokens"
echo "   2. Export token: export SUPABASE_ACCESS_TOKEN=your-token"
echo "   3. Link project: supabase link --project-ref fgyssizbuggjqsarwiuj"
echo "   4. Run migrations: supabase db push"
echo ""
echo "Option 3: Enable Direct Connections (For terminal access)"
echo "   1. Go to: https://supabase.com/dashboard/project/fgyssizbuggjqsarwiuj/settings/database"
echo "   2. Enable 'Direct connections'"
echo "   3. Allow your IP address"
echo "   4. Run: npm run migrate"
echo ""
echo "========================================"
echo ""
echo "📂 Migration file location:"
echo "   $(pwd)/ALL_MIGRATIONS.sql"
echo ""
echo "📊 File size:"
ls -lh ALL_MIGRATIONS.sql | awk '{print "   " $5}'
echo ""
echo "✅ Ready to run!"
echo ""

